print("---------------------------")
print("     Student Profile")
print("---------------------------")

name = input("Enter your name: ")
age = input("Enter your age: ")
university = input("Enter your university: ")
department = input("Enter your department: ")
favourite_language = input("Enter your favourite programming language: ")

print("\n---------------------------")
print("     Student Profile")
print("---------------------------")
print("Name                :", name)
print("Age                 :", age)
print("University          :", university)
print("Department          :", department)
print("Favourite Language  :", favourite_language)
print("---------------------------")